TestingSys.WebUI/TestingSys.WebUI/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TestingSys.Domain.Concreate;
using TestingSys.Domain.Entities;
using TestingSys.Domain.Infrastructure;
using TestingSys.Domain.Infrastructure.Filters;
using TestingSys.WebUI.Infrastructure.ViewModels;
using TestingSys.WebUI.Models;

namespace TestingSys.WebUI.Controllers
{
    /// <summary>
    /// Implementation of the choice of courses. 
    /// There is also sorting by name,
    /// complexity, and number of questions.
    /// </summary>
    [Log]
    [Authorize(Roles ="user")]
    public class CourseController : Controller
    {
        private static Dictionary<int, int> _questionIdList;
        private CourseRepository repository;
        public CourseController()
        {
            repository = new CourseRepository();
        }

        /// <summary>
        /// Implementing course selection and sorting.
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        public ActionResult DisplayCourse(string category, int page = 1, string complexity = null, int count = 0)
        {
            
            int PageSize = 2;
                CourseViewModel model = new CourseViewModel() 
                {
                     Courses = repository._Courses.Where(x=> category == null || x.Category == category).Where(x=>complexity == null||x.Complexity == complexity).Where(x=>count == 0|| x.Counter == count).OrderBy(x=>x.CourseId).Skip((page-1)*PageSize).Take(PageSize),
                     info = new InfoOfPage() 
                     {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = category == null ? repository._Courses.Count() : repository._Courses.Where(x => x.Category == category).Count(),
                     },
                     CurrentCategory = category
                };
                List<Course> _Courses = GetCourses();
                ViewBag.Complaxities = new SelectList(_Courses, "Complexity", "Complexity");
                return View(model);
        }
        /// <summary>
        /// Implementation of passing the test with a limited time.
        /// </summary>
        #region Display Test 
        [HttpGet]
        [AllowAnonymous]
        [ExceptionsDetail]
        public ActionResult TestList(int ? id ) 
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            else if (id <= 0)
            {
                throw new Exception("Error in class CourseList. Id less or equel null.");
            }
            var modelPage = repository._Questions.Where(x => x.CourseId == id).ToList();
            var minutsCounter = repository._Courses.Where(x => x.CourseId == id).Select(x => x.ExamTime).FirstOrDefault();
            var _Courses = repository._Courses.Where(x => x.CourseId == id).FirstOrDefault();
            var CourseName = _Courses.CourseName;

            ViewBag.CourseName = CourseName;
            MatchQuestionsToCategoryId(modelPage);
            ViewBag.MinutsCounter = minutsCounter;


            return View(modelPage);
        }

        /// <summary>
        /// Data validation and adding data to the database.
        /// </summary>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult TestList(FormCollection form, int? id) 
        {
            int trueCounter = 0;
            int falseCounter = 0;
            Exam exam = new Exam { StudentId = Convert.ToInt32(Session["StudentId"]), Date = DateTime.Now };
            List<ExamCategory> examCategories = new List<ExamCategory>();
            foreach (var item in _questionIdList)
            {
                if (form[item.Key.ToString()] == null)
                    continue;
                string result = form[item.Key.ToString()];
                string dbAnswer = GetRightAnswers._GetRightAnsweers(item.Key);

                bool isNewCategory = true;
                foreach (ExamCategory examCategory in examCategories.Where(x => x.CategoryId == item.Value))
                {
                    isNewCategory = false;
                    if (result == dbAnswer)
                    {
                        examCategory.TrueCounter += 1;
                        trueCounter += 1;
                    }
                    else
                    {
                        examCategory.FalseCounter += 1;
                        falseCounter += 1;
                    }
                }

                if (!isNewCategory) continue;

                ExamCategory newExamCategory = new ExamCategory { CategoryId = item.Value, TrueCounter = 0, FalseCounter = 0 };
                examCategories.Add(newExamCategory);
                if (result == dbAnswer)
                {
                    newExamCategory.TrueCounter += 1;
                    trueCounter += 1;
                }
                else
                {
                    newExamCategory.FalseCounter += 1;
                    falseCounter += 1;
                }
            }
            exam.TrueCounter = trueCounter;
            exam.FalseCounter = falseCounter;
            exam.Point = trueCounter * 2;

            using (DataContext context = new DataContext()) 
            {
                context.Exams.Add(exam);
                context.SaveChanges();
            }


            return RedirectToAction($"DisplayResultDatas/{id}", "Result");
        }
        #endregion


        /// <summary>
        /// A client with the admin role can add tests to the course or create a new course.
        /// </summary>
        #region CreateCourse
        [HttpGet]
        [AllowAnonymous]
        public ActionResult CreateCourse() 
        {
            List<Course> _Courses = GetCourses();
            ViewBag.Categories = new SelectList(_Courses, "CourseId", "Category");
            ViewBag.Complaxities = new SelectList(_Courses, "Complexity", "Complexity");
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCourse(FormCollection form) 
        {
            string Title = form["title"];
            string Answer = form["answer"];
            string CategoryId = form["Categories"];
            string ChoiceOne = form["choiceOne"];
            string ChoiceTwo = form["choiceTwo"];
            string ChoiceThree = form["choiceThree"];
            string ChoiceFour = form["choiceFour"];
            int c_Id = Convert.ToInt32(CategoryId);

            var _Counter = repository._Questions.Where(x => x.CourseId == c_Id).Count();

            Question _Question = new Question() 
            {
                Title = Title,
                Answer = Answer,
                CourseId = c_Id,
                AddedTime = DateTime.Now,
                ChoiceOne = ChoiceOne,
                ChoiceTwo = ChoiceTwo,
                ChoiceThree = ChoiceThree,
                ChoiceFour = ChoiceFour,
            };
            using (DataContext context = new DataContext()) 
            {
                var CourseDatas = context.Courses.Find(c_Id);
                CourseDatas.Counter = _Counter + 1;
                context.Questions.Add(_Question);
                context.Entry(CourseDatas).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();
            }
            return RedirectToAction("DisplayAdminPage", "Admin");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(FormCollection form) 
        {
            string CategoryName = form["name"];
            string Time = form["time"];
            string Complexity = form["Complaxities"];

            Course _Course = new Course() { Category = CategoryName, Complexity = Complexity,CourseName = CategoryName, ExamTime = Convert.ToInt32(Time) };

            using (DataContext context =  new DataContext()) 
            {
                context.Courses.Add(_Course);
                context.SaveChanges();
            }
            return RedirectToAction("CreateCourse", "Course");
        }
        #endregion

        /// <summary>
        /// A client with the admin role can delete a course.
        /// </summary>
        #region DeleteCourse
        [HttpGet]
        [AllowAnonymous]
        public ActionResult CourseDelete() 
        {
            var CourseDatas = GetCourses();
            return View(CourseDatas);
        }

        [HttpGet]
        [AllowAnonymous]
        [ExceptionsDetail]
        public ActionResult CourseDatasDelete(int ? id) 
        {
            if (id <= 0)
            {
                throw new Exception("Error in class DeleteDataCourse. Id less or equel null.");
            }
            using (DataContext context = new DataContext()) 
            {
                var _DatasCourse = context.Courses.Find(id);
                context.Courses.Remove(_DatasCourse);
                context.SaveChanges();
            }
            return RedirectToAction("DisplayAdminPage", "Admin");
        }
        #endregion

        /// <summary>
        /// A client with the admin role can modify course data.
        /// </summary>
        #region editCourse
        [HttpGet]
        [AllowAnonymous]
        public ActionResult EditCourses() 
        {
            List<Course> CoursesDatas = GetCourses();
            return View(CoursesDatas);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult EditDatasCourse(int ? id) 
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            using (DataContext context = new DataContext()) 
            {
                Course _Courses = context.Courses.Find(id);
                if (_Courses != null)
                {
                    List<Course> GetCourse = GetCourses();

TestingSys.WebUI/TestingSys.WebUI/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestingSys.Domain.Concreate;
using TestingSys.Domain.Entities;
using TestingSys.WebUI.Infrastructure.ViewModels;

namespace TestingSys.WebUI.Controllers
{
    /// <summary>
    /// The Menu controller displays a menu for filtering data.
    /// </summary>
    public class NavigationController : Controller
    {
        NavigationRepository repository;
        public NavigationController()
        {      
            repository = new NavigationRepository();
        }

        [HttpGet]
        public PartialViewResult Menu(string category = null, string complexity = null, int count = 0)
        {
            List<Course> _Course = GetCourses._GetCourses();
            foreach (var itemCourse in _Course) 
            {
                for (int i=0;i<=itemCourse.CourseId;i++) 
                {
                    List<int> _CourseList = new List<int>();
                    var _counter = repository._Questions.Where(x=>x.CourseId == i).Count();
                    ViewBag.Counter = (count == 0) ? _counter : 0;
                }
            }
            ViewBag.SelectedCategory = category;
            ViewBag.SelectedComplexity = complexity;
            NavigationViewModel model = new NavigationViewModel
            {
                Categories = repository._Courses.Select(x => x.Category).Distinct(),
                Complexity = repository._Courses.Select(x => x.Complexity).Distinct(),
                CounterQuestions = repository._Courses.Select(x=>x.Counter).Distinct(),
                
            };
            return PartialView(model);
        }

        



        /// <summary>
        /// Cleaning unmanaged objects.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            repository.Dispose();
        }
    }
}

TestingSys.WebUI/TestingSys.WebUI/Views/Course/CourseDelete.cshtml
@model IEnumerable<TestingSys.Domain.Entities.Course>
@{
    ViewBag.Title = "CourseDelete";
    Layout = "~/Views/Shared/_LayoutAdmin_Second.cshtml";
}

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
    </head>
    <body>
        <main class="container">

            <section class="page-section resume-section p-3 p-lg-5 d-flex align-items-center" id="services">
                <div class="container">
                    <h2 class="text-center mt-0">Delete Courses.</h2>
                    <hr class="divider my-4" />
                    <div class="row justify-content-center">

                        @foreach (var itemCourse in Model)
                        {
                            <div class="col-lg-3 col-md-6 text-center">
                                <div class="mt-5">

                                    <h3 class="h4 mb-2">@itemCourse.CourseName</h3>
                                    <h4>@itemCourse.Complexity</h4>
                                    <p class="text-muted mb-0">An actual ACT @itemCourse.CourseName Test contains @itemCourse.Counter questions to be answered in @itemCourse.ExamTime minutes.</p>
                                    <p><a class=" btn btn-danger" href="~/Course/CourseDatasDelete/@itemCourse.CourseId">Delete.</a></p>
                                </div>
                            </div>
                        }
                    </div>
                </div>

            </section>

        </main>
    </body>
    </html>

TestingSys.WebUI/TestingSys.WebUI/Views/Course/CreateCourse.cshtml
@{
    ViewBag.Title = "CreateCourse";
    Layout = "~/Views/Shared/_LayoutAdmin_Second.cshtml";
}

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <link href="~/Content/css/mainForm.css" rel="stylesheet" />
    </head>
    <body>
        <main class="container">
            <div class="row my-4">
                <div class="col-lg-12 order-lg-2">
                    <ul class="nav nav-tabs ">
                        <li class="nav-item">
                            <a href="" data-target="#addQuestion" data-toggle="tab" class="nav-link active">Add Question</a>
                        </li>
                        <li class="nav-item">
                            <a href="" data-target="#addCategory" data-toggle="tab" class="nav-link">Add Category</a>
                        </li>
                    </ul>
                    <div class="tab-content py-4">
                        <div class="tab-pane active" id="addQuestion">

                            <div class="row">
                                <div class="col-md-12">
                                    @using (Html.BeginForm("CreateCourse", "Course", FormMethod.Post,
                                    new { enctype = "multipart/form-data" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div id="contact-form" class="form-container" data-form-container="">
                                            <div class="container">
                                                <h2 class="text-center">Add Question.</h2>

                                            </div>
                                            <div class="input-container">
                                                <div class="row">
                                                    <span class="req-input">
                                                        <span class="input-status" data-toggle="tooltip" data-placement="top" title="Enter the Question."> </span>
                                                        <input type="text" name="title" maxlength="250" placeholder="Enter the Question ..." required>
                                                    </span>
                                                </div>



                                                <div class="row" id="inputPad" style="padding:0px;">
                                                    <p>Select a category: </p>
                                                    @Html.DropDownList("Categories", null, new { @class = "form-control", style = "height:40px;" })

                                                </div>

                                                <div class="row" id="inputPad">
                                                    <span class="req-input">
                                                        <span class="input-status" data-toggle="tooltip" data-placement="top" title="Enter the Answer ..."> </span>
                                                        <input type="text" name="answer" maxlength="250" placeholder="Enter the Answer ..." required>
                                                    </span>
                                                </div>


                                                <div class="row">
                                                    <span class="req-input">
                                                        <span class="input-status" data-toggle="tooltip" data-placement="top" title="Enter First Choice"> </span>
                                                        <input type="text" name="choiceOne" maxlength="250" placeholder="Enter First Choice..." required>
                                                    </span>
                                                </div>
                                                <div class="row">
                                                    <span class="req-input">
                                                        <span class="input-status" data-toggle="tooltip" data-placement="top" title="Enter the second option"> </span>
                                                        <input type="text" name="choiceTwo" maxlength="250" placeholder="Enter the second option..." required>
                                                    </span>
                                                </div>
                                                <div class="row">
                                                    <span class="req-input">
                                                        <span class="input-status" data-toggle="tooltip" data-placement="top" title="Enter the third option"> </span>
                                                        <input type="text" name="choiceThree" maxlength="250" placeholder="Enter the third option..." required>
                                                    </span>
                                                </div>
                                                <div class="row">
                                                    <span class="req-input">
                                                        <span class="input-status" data-toggle="tooltip" data-placement="top" title="Enter Fourth option"> </span>
                                                        <input type="text" name="choiceFour" maxlength="250" placeholder="Enter Fourth  option..." required>
                                                    </span>
                                                </div>
                                                <br />
                                                <div class="row submit-row">
                                                    <button type="submit" class="btn btn-success">Add Question</button>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>


                            </div>
                            <!--/row-->
                        </div>

                        <div class="tab-pane" id="addCategory">

                            <div class="form-group row">

                                <div class="col-lg-12">
                                    @using (Html.BeginForm("CreateCategory", "Course"))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div id="contact-form" class="form-container" data-form-container="">
                                            <div class="container">
                                                <h2 class="text-center">Add Category.</h2>
                                            </div>
                                            <div class="input-container">
                                                <div class="row">
                                                    <span class="req-input">
                                                        <span class="input-status" data-toggle="tooltip" data-placement="top" title="Enter Category Name..."> </span>
                                                        <input type="text" name="name" placeholder="Category Name...">
                                                    </span>
                                                </div>

                                                <div class="row" style="">
                                                    <p style="padding:0px;margin:0px;" >Choose Time: </p>
                                                    <input class="form-control" type="number" name="time" min="0" max="60" placeholder="Enter the Time..." required>
                                                </div>



                                                <div class="row" id="inputPad" style="padding:0px;">
                                                    <p style="padding:0px;margin:0px;">Choose difficulty: </p>
                                                    @Html.DropDownList("Complaxities", null, new { @class = "form-control", style = "height:40px;" })

                                                </div>

                                                <br />
                                                <div class="row submit-row">
                                                    <button type="submit" class="btn btn-success">Add Category</button>
                                                </div>
                                            </div>
                                        </div>

                                    }
                                </div>
                                <br />


                            </div>



                        </div>
                    </div>
                </div>

            </div>
        </main>

        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    </body>
    </html>

TestingSys.WebUI/TestingSys.WebUI/Views/Course/DisplayCourse.cshtml
@model TestingSys.WebUI.Infrastructure.ViewModels.CourseViewModel
@using TestingSys.WebUI.Infrastructure.Helpers
@{
    ViewBag.Title = "DisplayCourse";
}

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
    </head>
    <body>
        <main>
            @section Menu
            {
                @Html.Action("Menu", "Navigation")
                
            }
            <section class="page-section " id="services">
                <div class="container">
                    <h2 class="text-center mt-0">Courses</h2>
                    <hr class="divider my-4" />
                    <div class="row justify-content-center">

                        @foreach (var itemCourse in Model.Courses)
                        {
                            <div class="col-lg-3 col-md-6 text-center">
                                <div class="mt-5">

                                    <h3 class="h4 mb-2">@itemCourse.CourseName</h3>
                                    <h4>@itemCourse.Complexity</h4>
                                    <p class="text-muted mb-0">An actual ACT @itemCourse.CourseName Test contains @itemCourse.Counter questions to be answered in @itemCourse.ExamTime minutes.</p>
                                    <p><a class=" btn" href="~/Course/TestList/@itemCourse.CourseId">Pass the test</a></p>
                                </div>
                            </div>

                        }
                    </div>
                </div>

            </section>

            <div class="btn-group pull-right" style="margin-left: 20px;">
                @Html.PageLinks(Model.info, x => Url.Action("DisplayCourse", new { page = x }))
            </div>

            <hr />



            <section class="page-section bg-primary" id="about">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-8 text-center">
                            <h2 class="text-black-50 mt-0">About Us</h2>
                            <hr class="divider light my-4" />
                            <p class="text-black-50 mb-4">Our goal: to offer effective digital testing to students around the world, a more pleasant user experience and better knowledge retention.</p>

                        </div>
                    </div>
                </div>
            </section>
        </main>
        
    </body>
    </html>

TestingSys.WebUI/TestingSys.WebUI/Views/Course/EditCourses.cshtml
@model IEnumerable<TestingSys.Domain.Entities.Course>
@{
    ViewBag.Title = "EditCourses";
    Layout = "~/Views/Shared/_LayoutAdmin_Second.cshtml";
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <main class="container">

        <section class="page-section resume-section p-3 p-lg-5 d-flex align-items-center" id="services">
            <div class="container">
                <h2 class="text-center mt-0">Edit Courses.</h2>
                <hr class="divider my-4" />
                <div class="row justify-content-center">

                    @foreach (var itemCourse in Model)
                    {
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="mt-5">

                                <h3 class="h4 mb-2">@itemCourse.CourseName</h3>
                                <h4>@itemCourse.Complexity</h4>
                                <p class="text-muted mb-0">An actual ACT @itemCourse.CourseName Test contains @itemCourse.Counter questions to be answered in @itemCourse.ExamTime minutes.</p>
                                <p><a class=" btn btn-danger" href="~/Course/EditDatasCourse/@itemCourse.CourseId">Edit.</a></p>
                            </div>
                        </div>
                    }
                </div>
            </div>

        </section>

    </main>
</body>
</html>

TestingSys.WebUI/TestingSys.WebUI/Views/Course/EditDatasCourse.cshtml
@model  TestingSys.Domain.Entities.Course
@{
    ViewBag.Title = "EditDataCourse";
    Layout = "~/Views/Shared/_LayoutAdmin_Second.cshtml";
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link href="~/Content/css/mainForm.css" rel="stylesheet" />
</head>
<body>
    <main class="container">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("EditDatasCourse", "Course", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div id="contact-form" class="form-container" data-form-container="">
                        <div class="container">
                            <h2 class="text-center">Edit @Model.CourseName Course</h2>
                        </div>
                        <div class="input-container">
                            <div class="row">
                                <span class="req-input">
                                    <span class="input-status" data-toggle="tooltip" data-placement="top" title="Edit the Course name."> </span>
                                    <input type="text" name="category" maxlength="50" placeholder="Edit the Course name..." required>
                                </span>
                            </div>
                            <div class="row" style="">
                                <p style="padding:0px;margin:0px;">Edit Time: </p>
                                <input class="form-control" type="number" name="time" min="0" max="60" placeholder="Enter the Time..." required>
                            </div>
                            <br />
                            <div class="row submit-row">
                                <button type="submit" class="btn btn-success">Edit</button>
                            </div>
                        </div>

                    </div>


                }
            </div>
        </div>
    </main>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>